### ISSUE TITLE
logreduce

### ISSUE THREAD

**Issue by jayvdb** [jayvdb/pypidb#46]
https://logreduce.softwarefactory-project.io/ has disappeared.

https://softwarefactory-project.io/cgit/ also doesnt mention logreduce.

@TristanCacqueray / @sf-ci , I see you are the maintainer of https://pypi.org/project/logreduce/; do you know what has happened?

**Comment by TristanCacqueray** [comment]
We recently dropped a wildcard DNS record for the sf-project.io domain and forgot to add the logreduce entry. That should be fixed now.

Logreduce can be found in the cgit interface, it is: https://softwarefactory-project.io/cgit/logreduce/

**Comment by jayvdb** [comment]
Thanks. I'll fix it.
